conventional-commits/conventionalcommits.org

lang/es/spec/v1.0.0-beta.1.md

feat(showcase): add angular and karma

---

js/anchorli.js

Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`

spelling: elements

---

index.md

feat: Add explicit differences between body and footer in specs

---

lang/pl/spec/v1.0.0-beta.2.md
lang/pl/spec/v1.0.0-beta.md

see issue https://github.com/conventional-changelog/conventionalcommits.org/issues/46

feat(lang): polish translation for 1.0.0-beta.2

---

lang/zh-Hans/index.md
lang/zh-Hans/spec/v1.0.0-beta.1.md
lang/zh-Hans/spec/v1.0.0-beta.2.md
lang/zh-Hans/spec/v1.0.0-beta.md

feat(lang): update Chinese translations to 1.0.0-beta.2

---

lang/pl/index.md
lang/pl/spec/v1.0.0-beta.1.md
lang/pl/spec/v1.0.0-beta.2.md
lang/pl/spec/v1.0.0-beta.md

Some fixes as I missed some things last time.

fix: polish typos fix and index pointing to beta.2

---

index.md

Docs: Add clarification on commit type casing

---

index.md

Add imperative present tense requirement.
Closes #84 #77

feat: add imperative present tense requirement

---

content/next/index.md

Add bumped

---

content/next/index.md

pr with conventional commits badge https://github.com/LeDDGroup/scroll-utility/pull/29 :-)

docs: add scroll-utility to list

---

config.yaml
content/v1.0.0-beta.2/index.es.md
themes/conventional-commits/static/css/scss/layout/_welcome.scss

Hello!
Love the initiative on this project!
I'm a Spanish native speaker and noticed that the main title didn't make much sense (comparing with the English one). 
I also took the time to read and modified some other words.
Thanks!

docs: Main title and small general improvements

---

config.yaml
content/v1.0.0-beta.2/index.fr.md

Hey, I propose a French translation for conventional commits !
I'm not sure to follow the French translation as and when, but if I have time I'll think about it!

feat: Adding French translation

---

content/next/index.md

This is not my project but I learned about Conventional Commits because I decided to contribute back to Monica, so I believe it deserves to be in the list for spreading the word about your great initiative. And of course, the project is cool, too! :)

Add Monica to the list of projects

---

themes/conventional-commits/package-lock.json
themes/conventional-commits/package.json

`lodash` had a security alert breaking several of our projects.

chore: fix security vulnerabilities reported by npm audit

---

content/next/index.md

Use closes instead fixes keyword in order to reference an "issue" as it
can be either related to a bug or a feature request according to the
commit typology.

style: allow footer reference to be more generic regarding the type

---

config.yaml
themes/conventional-commits/static/css/scss/layout/_welcome.scss

If approved, fixes #131
I hope this is what you had in mind - if not, please let me know. First contribution here.

Add summary button to welcome section

---

themes/conventional-commits/package.json

fix: node-sass problem when local development

---

content/v1.0.0-beta.4/index.fr.md

Adding french translation for 1.0.0-beta.4
Late again ^^'

feat: Add french translation for 1.0.0-beta.4

---

config.yaml
content/v1.0.0-beta.4/index.ko.md

I hope that this would be useful for Korean developers :)

feat: Add Korean translation

---

config.yaml
content/v1.0.0-beta.4/index.pt-br.md

feat(lang): add brazilian portuguese (pt-br) language

---

config.yaml
content/v1.0.0-beta.4/index.zh-tw.md

Thank you all for creating this project.
I think this translation could gain more visibility in Taiwan & Hong Kong.

feat(lang): Add zh-TW translation for version v1.0.0-beta.4

---

content/v1.0.0-beta.4/index.ko.md

There are some changes in Korean translation:
- Fixed some typos
- More natural refinement of previous translation

docs: update Korean translation

---

content/next/index.md

Thank you for CC! Adopting it made my project much easier to manage / keeping an overview! (3300+ commits in)

docs(users): add thi.ng/umbrella to project list

---

content/next/index.md

docs: add Commitsar to next

---

content/v1.0.0-beta.4/index.md
content/v1.0.0-beta.4/index.ru.md

fix: some typos in russian description about `mhy`

docs: add notes about sharec project

---

content/v1.0.0/index.md

docs: add new project dcyou/resume

---

content/v1.0.0/index.fr.md

following request: #189
I also added my own project to the bottom

feat(lang): add french language

---

content/next/index.md

I hope I followed all of the rules! This commit is my first using the Conventional Commit style.

fix(lang): singular "parenthesis" to plural "parentheses"

---

content/v1.0.0/index.ja.md

feat(lang): add japanise language (v1.0.0)

---

content/v1.0.0-beta.4/index.pt-br.md

Added links to semver pt-br, for better user experience

fix(br): Update semver links pt-br docs

---

content/v1.0.0-beta.4/index.ko.md

fix(ko): fixed typo

---

content/next/index.md
content/v1.0.0/index.fr.md
content/v1.0.0/index.md

🤗  Thanks to conventional commits for helping the [TinaCMS](https://github.com/tinacms/tinacms) team keep a clean changelog. We automated the check with husky ✨

docs: add TinaCMS to projects

---

content/v1.0.0/index.ko.md

add translation translations for related tools and project
improve a translation in faq

fix(ko): improve and add translation

---

content/v1.0.0-beta.4/index.it.md
content/v1.0.0/index.md

The minor adjustment is to align to a new feature and to have a better italian translation.

docs(tooling): minor adjustment and italian translation for Conventional Commit

---

content/v1.0.0/index.md

docs: add VSCode Conventional Commits

---

content/next/index.md
content/v1.0.0/index.md

Updated docs to include the company [Uno Platform](https://platform.uno) who use CC.

Add company Uno platform to list

---

content/next/index.md

Add [undercut](https://undercut.js.org/) library to the `Projects Using Conventional Commits`.

docs: add undercut to projects

---

content/v1.0.0/index.md

Add the following tools for Conventional Commits:
- commitizen/cz-cli
- commitizen-tools/commitizen
- commitlint
- gitlint
- semantic-release

docs(tooling): add several tools to the list

---

content/next/index.md

[commitizen-tools/commitizen](https://github.com/commitizen-tools/commitizen)

docs(tooling): add python implemented commitizen-tools as Tools

---

README.md

Make some minor changes to improve consistency and appearance. (Fix some weird brackets, and styling in the thank you section)
I'm not completely sure if the thank you section styling is intentional, but I personally think it looks better this way. I can revert it if necessary.

chore(readme): fix consistency/appearance

---

content/next/index.md

This add [cocogitto](https://github.com/oknozor/cocogitto/) to the tooling list.

docs(tooling): add cocogitto to the tooling list

---

content/v1.0.0-beta.3/index.es.md

This PR contains a fix for two broken links in the latest available version of the Spanish text

Fix: broken links

---

config.yaml
content/v1.0.0/index.zh-hans.md

Keeping up with new version of Conventional Commits.
Refine some translation, especially the Summary, it's so important that MUST use clear and precise expression.
Some terms see footers.
Conventional-Commit: 约定式提交
footer[s]: 脚注
scope: 范围, 不应该使用作用域, 面向人读的文档应该使用普通词汇.
token: 令牌
Specification: 规范

feat(zh-hans): v1.0.0 zh-hans translation

---

content/v1.0.0/index.ja.md

I updated the `index.ja.md` because the current translation is not so natural and there are some mistranslation.

feat(ja): Improve fluency of the Japanese translation

---

content/about/index.md

Greetings. I just fixed a URL.

docs(about): fix tool link

---

themes/conventional-commits/static/css/scss/components/_dropdown.scss

fix(dropdown): prevent antialised blur bug on Chrome/Windows

---

content/v1.0.0/index.ru.md

Case:
Done:
- fixed level of header for 'Examples'
- renamed header of examples for common style

fix(ru): section 'Examples'

---

content/v1.0.0/index.es.md

Hi. 
This pull request add a complete translation for Spanish (v1.0.0)

docs(v.1.0.0): add spanish translations for v1.0.0

---

content/next/index.md

fixes https://github.com/conventional-commits/conventionalcommits.org/issues/388

fix: readd impertive wording FAQ

---

content/about/index.md

I wanna add new tooling for Conventional Commits.
https://github.com/ramsey/conventional-commits

docs(about): add ramsey/conventional-commits in about page.

---

content/v1.0.0/index.pt-br.md

I have corrected a spelling error and an incorrect sentence.
I also translated a text that was in English to pt-br
---
resolve #337

fix: misspellings and text not translated to pt-br

---

content/about/index.md

Added a new tool developed in Go to parser your git commit messages into a change log message based on conventional commits specification.

docs(about): add a new tool developed in Go

---

themes/conventional-commits/static/css/scss/abstracts/_mixins.scss
themes/conventional-commits/static/css/scss/abstracts/_variables.scss
themes/conventional-commits/static/css/scss/components/_dropdown.scss
themes/conventional-commits/static/css/scss/layout/_header.scss
themes/conventional-commits/static/css/scss/layout/_welcome.scss

Fixed an overflow problem on small screens
**Bug**
**Fix**

fix: menu overflow in small screens

---

content/v1.0.0/index.md

https://psychology.stackexchange.com/questions/13946/why-does-the-brain-skip-over-repeated-the-words-in-sentences

docs: remove repeated "the"

---

config.yaml
content/v1.0.0/index.nl.md

This will add the Dutch translation.

feat(lang): add Dutch translation

---

content/about/index.md

I added freeCodeCamp to the projects list.
https://github.com/freeCodeCamp/freeCodeCamp/pull/15940

docs(about): add freeCodeCamp to projects list

---

content/about/index.md

Adds https://github.com/PSanetra/git-semver to about page.

docs(about): Add git-semver cli tool

---

content/v1.0.0/index.zh-hans.md

This patch let visitor can jump to specific page written in language that they are using.
Only in zh-Hans.

fix(zh-Hans): match language specific version semver page

---

content/about/index.md
content/next/index.md

CC was the kind of thing I've been always looking for, glad I found it.
Now I no longer have to struggle with changelog generation and version bumping with a custom solution for my project.

docs: Add GearLock in projects list

---

config.yaml
content/v1.0.0/index.ro.md

Hello,
I have translated the website into the Romanian language.
It's awesome that exists such a website. Thank you for this kind of learning documentation! 🙌🏼
P.S: Please add the label `hacktoberfest-accepted` to this PR if you consider 🙏🏻
Cheers 🍻,
Vlad

Romanian 🇷🇴 language added

---

content/v1.0.0/index.fr.md

I've reviewed the whole text to make it more natural for a native french speaking.

fix: Fix grammar and consistency in french translation

---

content/about/index.md

- add link to thi.ng/monopub release tool
- update thi.ng/umbrella project description

Add/update tool/project links

---

content/about/index.md

feat: add cz-git to commit message generators section

---

content/v1.0.0-beta.4/index.fr.md

A few corrections to the conjugation and vocabulary on french page

fix(fr): correct typo on French page

---

content/v1.0.0/index.zh-hans.md

Convert traditional Chinese to simplified Chinese, "說" is a traditional Chinese word. The word should be changed to "说".

fix(zh-hans): fix translation of "說" word

---

config.yaml
content/v1.0.0/index.pl.md

Improved the Polish language description to better match other European versions and ensure natural, clear wording.

feat(pl): update Polish specification description for clarity and consistency
