conventional-commits/conventionalcommits.org

- index.md
* Try to normalize header "after" spacing
* Clarify fixing typos v. misunderstandings v. out-of-spec
* Cover how to version your own spec extensions
> docs: add clarifications and formatting to FAQ

- index.md
Use the present tense imperative mood in the example commit message. 
So, `feat(parser): add ability to parse arrays` , not `feat(parser): adds ability to parse arrays`.
Conventional Commits may not need to specify present tense, imperative mood for verbs. But I think at least the example should use the common present tense, imperative mood practice.
Maybe Conventional Commits should specify. Makes for a stronger convention.
References:
+ [Commit Verbs 101: why I like to use this and why you should also like it.][]: "Always use the verbs in Imperative Present tense. Don’t use Past or Present Continuous tenses for commits."
+ [Git book on commit message recommendations][]: "It’s also a good idea to use the imperative present tense in these messages. In other words, use commands. Instead of …
> fix(example): present tense imperative. "adds ability" -> "add ability".

- index.md
`uPortal-home` (previously known as `AngularJS-portal`) and `uPortal-application-framework` (previously known as `uw-frame`) have both adopted Conventional Commits.
+ uPortal-home in its [PR 666](https://github.com/UW-Madison-DoIT/angularjs-portal/pull/666)
+ uPortal-application-framework in its [PR 487](https://github.com/UW-Madison-DoIT/uw-frame/pull/487)
> feat(showcase): add uPortal-home and app framework

- index.md
fixes #16 
Move session up along with in the list of types to make it more stands out.
> Callout "Others" commit type

- _config.yml
- lang/zh-Hans/index.md
- lang/zh-Hans/spec/v1.0.0-beta.1.md
- lang/zh-Hans/spec/v1.0.0-beta.md
This PR adds simplified Chinese translation to Conventional Commits.
Some minor formats are modified to fit Chinese, e.g., since we don't have upper case and lower case in Chinese, bold format is used for translating `MUST`, `MAY`, etc.
> feat(lang): add zh-Hans translation

- index.md
- lang/es/index.md
- lang/es/spec/v1.0.0-beta.1.md
- lang/es/spec/v1.0.0-beta.md
- lang/it/index.md
- lang/it/spec/v1.0.0-beta.1.md
- lang/it/spec/v1.0.0-beta.md
- lang/pl/index.md
- lang/pl/spec/v1.0.0-beta.1.md
- lang/pl/spec/v1.0.0-beta.md
- lang/zh-Hans/index.md
- lang/zh-Hans/spec/v1.0.0-beta.1.md
- lang/zh-Hans/spec/v1.0.0-beta.md
- spec/v1.0.0-beta.1.md
- spec/v1.0.0-beta.md
Closes #30
This PR unifies `Major` to `MAJOR` to follow SemVer convention better, with `verb` corrected to `noun` (I'm treating this as a typo since the de facto standard is noun, so no new version is added with all old docs modified). Translations are also corrected (I can't read them, done with Google translation), except that Polish itself has used `noun` instead of `verb`. For Chinese version, some punctuation is optimized for better markdown layout.
> fix: minor typos

- index.md
I was pointed to the specification and wanted to just get started, which would have been possible with examples. Instead I did a lot of reading about the motivation for the spec, and the formal spec itself. I am hoping the examples will help other people see how simple the spec is and to just get started quickly.
> feat: added examples to the specification

- index.md
The @electron project is now using Conventional Commits in many of its repos. We also built a bot to help make sure every PR we ship follows the CC spec: https://github.com/probot/semantic-pull-requests
We also use `semantic-release` all over the place: https://github.com/search?utf8=%E2%9C%93&q=%22npm+run+semantic-release%22+%40electron&type=Code
> docs: add Electron to list of projects

- spec/v1.0.0-beta.2.md
It was in work for few months, but last night i released v2 of it. I'm using conventional commits for year or two, and thanks for that specification. I also have badge to the spec in most of my repos.
Let me know if something is not okey.
> fix: add spec compliant parser

- index.md
> Remove 'NOT recommended' wording from the 'Other types' paragraph discussing breaking changes

- content/next/index.md
Prior to this change, if a message had a block of text after the type and description then it was ambiguous as to whether it was a body or a footer. This change resolves the issue by specifying that a footer can only follow (and therefore requires) a body, rather than a description.
Fixes #98
> fix: Remove spec ambiguity between body and footer

- content/next/index.md
Blaze uses commitlint to ensure conventional commits are being written and it's really helped with automatically creating our change logs per package, in other words we now have some change logs!
> docs: add Blaze to list of projects

- content/next/index.md
* a few minor edits to get us back in alignment with [RFC-2119](https://tools.ietf.org/html/rfc2119).
* I also moved `standard-version` into the tools section, since it's a tool that applies the convention.
fixes #87
> docs: attempt to get us back in alignment with RFC-2119

- content/next/index.md
Based on discussion in #43 I've made an effort to describe a new `!` character, which can optionally be used in the header to indicate a breaking change.
The value I see in making this optional:
* the feature will be available for folks who would like to use it, but the spec doesn't drift away from angular's commit message format.
* tooling can more gradually move over to this new semantic construct.
I propose we wait and see how widely `!` is adopted, and consider making it a MUST in the future if it's seeing wide adoption.
CC: @DominicKramer, @apetro, @ofrobots
> feat: introduce ! for indicating breaking changes in header

- content/next/index.md
Conventional Commits is silent on the grammatical structure of commit
descriptions, but logs are easier to read if that structure is consistent.
Convert the examples to imperative mood so they all read similarly:
allow provided config object to extend other configs
correct spelling of CHANGELOG
add polish language
correct minor typos in code
More discussion of the topic:
https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
https://chris.beams.io/posts/git-commit/
> docs: use imperative mood in descriptions

- content/next/index.md
- content/v1.0.0-beta.1/index.md
- content/v1.0.0-beta.2/index.md
- content/v1.0.0-beta.3/index.md
- content/v1.0.0-beta.4/index.md
- content/v1.0.0-beta/index.md
In the context of the sentence, the verb "clean up" should be used rather than the noun "cleanup".
Explanation: https://grammarist.com/usage/cleanup-clean-up/
Dictionary reference: https://www.merriam-webster.com/dictionary/cleanup
> fix: fix grammatical error

- content/next/index.md
Now that I've had some experience using `!` in the wild, my opinion of how we should define the feature has changed a bit.
There are two incidents on my mind:
1. myself and my peers released a breaking change as a minor because we accidentally didn't rewrite the merge message (dropping the BREAKING CHANGE that we had in the description); this is currently fairly easy to do with GitHub's UI.
1. motivated by the above incident, we started using `!` in our commit messages -- however, history repeated itself and we merged a commit with `!` in the header, but no BREAKING CHANGE in body.
In the process of these two incidents, I came around to @DominicKramer and @ofrobots' argument that having an indicator of a breaking change in the header of the commit message itself should be enough to …
> docs: update ! to better reflect how it is  used in the wild

- content/next/index.md
Using CC in my project :fire:. It is quite new yet, but it's getting there.
Also the latest feature encourages users to use the `fire/commit` command which helps commiting conventionally from terminal using [php-commitizen](https://github.com/damianopetrungaro/php-commitizen).
> docs: add yii2-firestarter to the project list

- content/next/index.md
Working from @JeanMertz's suggestions in #179 proposes a few new rules related to differentiating between footer and body sections of commit message.
Builds on top of [git trailers](https://git-scm.com/docs/git-interpret-trailers) and [RFC822](https://www.ietf.org/rfc/rfc822.txt) folding conventions.
_(I also did some minor editing, and removed some text I felt was redundant, given that the spec is growing a little bit)._
fixes: #170 
CC: @epage, @JeanMertz, @blowmage
> feat: reduce ambiguity around footer/body

- content/v1.0.0/index.md
Addresses a formatting bug in [Summary](https://www.conventionalcommits.org/en/v1.0.0/#summary).
> fix: 'ci:' type markdown syntax

- content/v1.0.0-beta.4/index.ja.md
`issuen` is typo and I fix it.
> fix(ja): Fix Japanese translation typo

- content/next/index.md
A commit doesn't really “conform” to any one commit type if it contains changes matching other commit types. So better to call this “containing changes” of different types. (Or “matching” more than one of the commit types, or some phrasing like that.)
> fix: rephrase “more than one type” question

- content/v1.0.0/index.md
GitHub: https://github.com/lppedd/idea-conventional-commit
JetBrains Plugins Repository: https://plugins.jetbrains.com/plugin/13389-conventional-commit
> docs(tooling): add Conventional Commit for IntelliJ-based IDEs

- content/v1.0.0/index.ko.md
I added a missing backtick in Korean Translation v1.0.0
> fix(ko): added a missing backtick

- content/next/index.md
- content/v1.0.0/index.md
I recently released the first stable version of [Pyhist](https://github.com/jgoodman8/pyhist), a Python utility to automatically update the package version from the git history and generate the Changelog. This tool is inspired by the Standard-Version project.
Since there isn't any similar tool for Python, I think it will be very beneficial for the Python ecosystem the support and development of this utility. So, I would like to include it in the list, to spread the news in the dev's community.
> docs: add pyhist to tooling list

- content/next/index.md
- content/v1.0.0/index.md
:wave: Just a little thing I noticed while reading up on the details of the new `!` suffix for breaking changes.
> docs: fix "ommitted" typo

- content/v1.0.0/index.md
They were in previous versions, or at least the "parser" which is much more nowadays than just a parser.
Or should I move them all above? Hm. Anyway, I don't want to aggressively promote or anything, they are just pretty useful for those folks interested in CC. They were born and are used in @standard-release and similar things.
> Add more Conventional Commit tools to the list

- content/next/index.md
- content/v1.0.0/index.md
Add additional tool supporting conventional commits to the tooling list.
> docs: add git-mkver to tooling

- Dockerfile
This PR fixes building docker image by adding missing dependencies to nginx:alpine. I have tested this on my local machine and it built and served website successfully.
I am not sure if this is related to #291 or not, since there is no clue about broken things in that issue.
> fix(deps) add missing dependencies in Dockerfile

- content/next/index.md
- content/v1.0.0/index.md
Adding the tool Conventional Commits Next Version to the tooling section.
> docs: adding Conventional Commits Next Version

- content/next/index.md
Fix the link, and a small typo about the description
> fix(tooling): Fix go-conventional-commit link

- content/next/index.md
Refactoring by definition "is the process of changing a software system in such a way that it does not alter the external behavior of the code..." So, a refactoring cannot introduce a breaking change, otherwise it is not a refactoring anymore. Using `refactor` commit type and the breaking change marker `!` is a contradiction.
> fix: replace "refactor!" with "feat!"

- content/next/index.md
- content/v1.0.0/index.id.md
- content/v1.0.0/index.md
- content/v1.0.0/index.th.md
Semantic Versioning is the name of the specification, hence it is a proper noun and this patch corrects the casing.
> docs: correcting casing on proper noun

- content/next/index.md
- content/v1.0.0/index.md
I have created a PHP tool [php-conventional-changelog](https://github.com/marcocesarato/php-conventional-changelog) to generate a changelog from a project's commit messages and metadata following the Conventional Commit and automate versioning.
I created it because I haven't found a similar solution for php.
> docs(tooling): add php-conventional-changelog to the tooling list

- content/next/index.md
- content/v1.0.0/index.md
I am author of [Changeloguru](https://github.com/haunt98/changeloguru). It is a tool to auto generate changelog (`CHANGELOG.md`) from conventional commits.
Example [CHANGELOG](https://github.com/haunt98/changeloguru/blob/main/CHANGELOG.md)
> docs: adding changeloguru projects to next and v1.0.0 content

- content/next/index.md
- content/v1.0.0/index.md
The https://github.com/leodido/go-conventionalcommits contains a very fast (see [benchmarks](https://github.com/leodido/go-conventionalcommits#performances)) Go library to parse Conventional Commits.
It uses finite-state machines to implement the parsing.
Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>
> docs: add go-conventionalcommits to the tools list

- content/about/index.md
- content/next/index.md
This was previously merged in #305 but somehow never end up on the website. 
Also it was on the wrong section.
> docs(tooling): add cocogitto to the tooling list

- content/about/index.md
- content/next/index.md
I have designed a new conventional commit based tool, written in Go. It utilises conventional commits to automatically bump a semantic version in any file and tag the repository for release. I would appreciate it if I could add it to the list of existing tools. Thanks. 
Keep up the good work!
> docs(tooling): add uplift to the list of existing tooling

- content/next/index.md
- content/v1.0.0/index.de.md
- content/v1.0.0/index.fr.md
- content/v1.0.0/index.id.md
- content/v1.0.0/index.ja.md
- content/v1.0.0/index.ko.md
- content/v1.0.0/index.md
- content/v1.0.0/index.ru.md
- content/v1.0.0/index.th.md
- content/v1.0.0/index.uk.md
- content/v1.0.0/index.zh-hans.md
- content/v1.0.0/index.zh-hant.md
Thanks for all your input in #348. I mostly agree with you.
I think whether to start header capitalized or not is opinionated, as long as it is consistent. I find it more natural to capitalize it but e.g. [Angular conventions](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-header) states, it must not be capitalized. So I will leave it out of this PR. Changing it in all examples would anyway be worth an own issue and pull request in my opinion.
I felt given a shortened abstract example is nicer to read than quoting [Chris Beam's exmaple](https://chris.beams.io/posts/git-commit/#why-not-how). 
As a side note regarding *"Issues trackers can change over time"*. I think they shouldn't as they contain important information from also non technical stakeholders. But …
> docs: improve example

- README.md
```
docs(readme): 📝 update metadata badge
Update the metadata badge to use the new conventional commits icon in https://simpleicons.org/?q=conventional%20commits.
Closes: #437
```
Issue #437 description:
> ## 🏷️ Description
> 
> I created and published a conventional commits icon in the [official simpleicons.org repository](https://simpleicons.org/?q=conventional%20commits):
> 
> ![Conventional Commits SVG in simpleicons.org](https://user-images.githubusercontent.com/16791848/160967025-20149745-388c-43fd-930c-c1df4078f8c4.png)
> 
> You can see the:
> 
> * [`simple-icons` GitHub issue](https://github.com/simple-icons/simple-icons/issues/7027)
> * [`simple-icons` GitHub pull request](https://github.com/simple-icons/simple-icons/pull/7200)
> 
> ## 👀 Example
> 
> This markdown:
> 
> …
> docs(readme): 📝 update metadata badge

- content/v1.0.0/index.it.md
> docs(it): add missing colon in `Refs` token

- config.yaml
I realized that the webpage didn't have the Turkish translation, but @umutphp had already translated it in #255. But it was not added to the config.yaml.
> feat: add existent turkish translation to config

- content/v1.0.0/index.pt-br.md
There were some examples including <refactor> type in a breaking
change commit. They were replaced by examples from the english
version.
Refs: #457.
> fix(pt-br): replace bad example for breaking changes in pt-BR version

- themes/conventional-commits/layouts/partials/header.html
Removed the translations length printed before the first dropdown option
BUG
FIX
> fix(theme): remove translations length from dropdown menu

- content/v1.0.0/index.fr.md
In french, a non-breakable space is required before every colons.
> fix(fr): add non-breakable spaces before colons

- content/v1.0.0/index.es.md
In Spanish, colon  is ```"dos puntos"```.
Replace word ```"punto y coma"``` to ```"dos puntos"```.
> fix(es): fixed incorrect Spanish words 

- config.yaml
- content/v1.0.0/index.ko.md
Fixed `메세지` → `메시지`.
Reference: [국립국어원 표준국어대사전](https://stdict.korean.go.kr/search/searchView.do?word_no=113651&searchKeywordTo=3)
> fix(ko): fix translation typo for message

- content/next/index.md
This solution is based on PR #214, to address Issue #165
While PR #214 describes a new footer `INITIAL STABLE RELEASE:`, here we also propose a short-hand `!!` syntax.
Closing this vacuum on how to deal with pre-release versions will allow automated tools to be able to deal with moving on from 0.Y.Z to 1.0.0.
> feat!: support promoting pre-release versions to 1.0

- themes/conventional-commits/static/css/scss/layout/_welcome.scss
- Adjusted the welcome button so that the text is aligned to the vertical center, improving visual appearance.
- By merging this Pull Request, the first view of pages in languages such as Chinese and Japanese, which use characters that are displayed larger than alphabets, will appear more aesthetically pleasing. 
- Moreover, it is unlikely to negatively impact the UI of pages in other languages, such as English, making this change beneficial overall.
- Please refer to the screenshots below for a comparison of the UI differences.
<details>
<summary>UI differences</summary>
| Before | After |
|--------|--------|
| <img width="1912" alt="image" src="https://github.com/conventional-commits/conventionalcommits.org/assets/94698042/5fb02e76-16ae-4c8d-9652-6b8f08425ab1"> | <img width="1912" …
> fix(welcome button): align text to vertical center

- content/v1.0.0/index.ko.md
Corrected spelling errors in Korean and modified parts that may have felt different in meaning when compared to the English version.
> fix(ko): fix translation typos and improve grammar

- content/about/index.md
Hello,
For the past few months I explored using Convention Commits in my project and because I have a lot of OSS projects to maintains I made a collection of tools.
They are mostly aimed at .NET developers because they are published as `dotnet tool` but they can be used by any one.
> docs(about): add `EasyBuild` projects to the list of tools

- README.md
Purely to make it easier to find the most readable version of the spec.
> docs: add link to website at top of README.md

- content/v1.0.0/index.id.md
-   Summary:
This update refines the documentation to fix formatting issues, improve grammar, and streamline the presentation without altering the core meaning.
-   Key Changes:
-   Polished sentence structure to enhance readability.
-   Fixed minor errors, such as inconsistent formatting.
-   Reason for Changes:
-   These changes aim to improve the quality of the documentation, making it clearer and easier to understand for users.
-   Additional Notes:
-   No substantive changes were made to the specifications—this is purely a presentation improvement.
> fix(id): improve and correct translation for better readability
